### ISSUE TITLE
Error message when creating or restarting dinghy VM

### ISSUE THREAD

**Issue by saikat** [codekitchen/dinghy#107]
From a fresh install, I got this when creating as well:

$ dinghy up
dinghy already running, restarting...
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
/usr/local/Cellar/dinghy/4.0.7/cli/dinghy/machine.rb:36:in `host_ip': undefined method `sub' for nil:NilClass (NoMethodError)
	from /usr/local/Cellar/dinghy/4.0.7/cli/dinghy/unfs.rb:93:in `plist_body'
	from /usr/local/Cellar/dinghy/4.0.7/cli/dinghy/plist.rb:28:in `plist_path'
	from /usr/local/Cellar/dinghy/4.0.7/cli/dinghy/plist.rb:9:in `up'
	from /usr/local/Cellar/dinghy/4.0.7/cli/dinghy/unfs.rb:17:in `up'
	from /usr/local/Cellar/dinghy/4.0.7/cli/cli.rb:185:in `start_services'
	from /usr/local/Cellar/dinghy/4.0.7/cli/cli.rb:78:in `up'
	from /usr/local/Cellar/dinghy/4.0.7/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.0.7/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.0.7/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.0.7/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:6:in `<main>'

**Comment by marclennox** [comment]
I'm seeing this also.  Looks like it's related to recent Docker updates (either machine 0.5.1 or docker 1.9.1).  Things were working fine with machine 0.5 and docker 1.9.0.

Dinghy is an awesome project, unfortunately it seems to break often as docker updates roll out.

**Comment by marclennox** [comment]
I think it has something to do with the HostName being blank in the dinghy ssh-config

```
Host dinghy
  HostName
  User docker
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /id_rsa
  IdentitiesOnly yes
  LogLevel ERROR
```

**Comment by marclennox** [comment]
Reverting to docker-machine 0.5.0 resolves the issue.

**Comment by codekitchen** [comment]
Yeah they have an annoying habit of changing the structure of the `docker-machine inspect` JSON output with each release lately. The joys of building on top of other early-stage software. Looks like the JSON path is now `Driver.Driver.IPAddress` instead of just `Driver.IPAddress`.

I've released v4.0.8 that is now compatible with docker-machine 0.5.1, as always upgrade instructions are @ https://github.com/codekitchen/dinghy#upgrading

I don't have a lot of great ideas about how to avoid these sorts of surprises in the future, unfortunately. If somebody frequently installed docker-machine dev builds from master and tested dinghy, that could do it, but realistically I just don't have time to do that, somebody else would have to take that on. I could also have dinghy refuse to work with a newer version of docker-machine than what it's been tested against, but that seems worse.

**Comment by marclennox** [comment]
Thanks @codekitchen.  I hear you, and I certainly appreciate the quick response.  I will try to periodically test dinghy against upcoming docker-machine builds to catch these earlier.

**Comment by codekitchen** [comment]
Thank you, that would be a huge help.
